### PR TITLE
[recipes] move resources from default into configure recipe

### LINKED ISSUE #110: Bug: Race Condition with a Bad Config
## Background

Currently, the `td-agent::default` recipe is responsible for installing TD agent, and configuring the main config file along with starting and enabling the `td-agent` service.

## Issue

The designated workflow suggests the recipe `td-agent::default` be included prior to using the custom resources (`td_agent_match`, etc) to setup the application based on your *own* requirements.  

The problem is that if you incorrectly configure `td-agent`, Chef is unable to correct the problem due to the `default` recipe attempting to start the service.  This causes failed Chef runs because the custom resources cannot change the offending configurations.

## Solution

Split the configuration/service resources in `td-agent::default` into their own recipe, potentially called `td-agent::configure`.  The `default` recipe logic will remain the same, and this solution will give more flexibility and reliability to the user on how to use the cookbook with custom resources.

### PR DESCRIPTION
**Pull request by jacknagz**
to @yyuu 
resolves #110 (additional context in the issue)

## Changes

* Split the resources defined in `td-agent::default` into their own recipe (this retains the previous behavior as well)
* Update unit tests
* Bump minor version

## Testing

* Locally with unit tests
* Locally with Kitchen

### CODE REVIEW

File: metadata.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@
 license          "Apache 2.0"
 description      "Installs/Configures td-agent"
 long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
-version          "3.1.0"
+version          "3.1.1"
```
Comment (yyuu) [inline metadata.rb]: 3.1.0 is current development/snapshot version and it's not yet released. You don't need to update version number.

**Comment by jacknagz** [comment]
@yyuu done! thanks for the review
